"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.api.contact_api import ContactApi  # noqa: E501


class TestContactApi(unittest.TestCase):
    """ContactApi unit test stubs"""

    def setUp(self):
        self.api = ContactApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contact_facultes_get(self):
        """Test case for contact_facultes_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
