"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.proposition_pae_links import PropositionPaeLinks
globals()['PropositionPaeLinks'] = PropositionPaeLinks
from osis_inscription_cours_sdk.model.proposition_pae import PropositionPae


class TestPropositionPae(unittest.TestCase):
    """PropositionPae unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionPae(self):
        """Test PropositionPae"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionPae()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
