"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.configuration_formulaire_inscription_cours import ConfigurationFormulaireInscriptionCours
from osis_inscription_cours_sdk.model.inscription_aun_cours import InscriptionAUnCours
globals()['ConfigurationFormulaireInscriptionCours'] = ConfigurationFormulaireInscriptionCours
globals()['InscriptionAUnCours'] = InscriptionAUnCours
from osis_inscription_cours_sdk.model.formulaire_inscription_cours import FormulaireInscriptionCours


class TestFormulaireInscriptionCours(unittest.TestCase):
    """FormulaireInscriptionCours unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormulaireInscriptionCours(self):
        """Test FormulaireInscriptionCours"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormulaireInscriptionCours()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
