"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.api.pae_valide_jury_api import PaeValideJuryApi  # noqa: E501


class TestPaeValideJuryApi(unittest.TestCase):
    """PaeValideJuryApi unit test stubs"""

    def setUp(self):
        self.api = PaeValideJuryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mon_pae_valide_jury(self):
        """Test case for mon_pae_valide_jury

        """
        pass


if __name__ == '__main__':
    unittest.main()
