"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.pae_valide_jury_links import PaeValideJuryLinks


class TestPaeValideJuryLinks(unittest.TestCase):
    """PaeValideJuryLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaeValideJuryLinks(self):
        """Test PaeValideJuryLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaeValideJuryLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
