"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.complement_de_formation import ComplementDeFormation


class TestComplementDeFormation(unittest.TestCase):
    """ComplementDeFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testComplementDeFormation(self):
        """Test ComplementDeFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ComplementDeFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
