"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.mini_formation import MiniFormation
globals()['MiniFormation'] = MiniFormation
from osis_inscription_cours_sdk.model.liste_mini_formations import ListeMiniFormations


class TestListeMiniFormations(unittest.TestCase):
    """ListeMiniFormations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListeMiniFormations(self):
        """Test ListeMiniFormations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListeMiniFormations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
