"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.formulaire_proposition_programme_annuel_inscriptions_dans_mini_formations import FormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations


class TestFormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations(unittest.TestCase):
    """FormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations(self):
        """Test FormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
