"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.13
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.pdf_en_cours import PdfEnCours


class TestPdfEnCours(unittest.TestCase):
    """PdfEnCours unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPdfEnCours(self):
        """Test PdfEnCours"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PdfEnCours()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
