"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.inscription_aun_cours import InscriptionAUnCours
globals()['InscriptionAUnCours'] = InscriptionAUnCours
from osis_inscription_cours_sdk.model.inscriptions_aun_partenariat import InscriptionsAUnPartenariat


class TestInscriptionsAUnPartenariat(unittest.TestCase):
    """InscriptionsAUnPartenariat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInscriptionsAUnPartenariat(self):
        """Test InscriptionsAUnPartenariat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InscriptionsAUnPartenariat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
