"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.8
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.formulaire_inscription_cours import FormulaireInscriptionCours
globals()['FormulaireInscriptionCours'] = FormulaireInscriptionCours
from osis_inscription_cours_sdk.model.inline_response200 import InlineResponse200


class TestInlineResponse200(unittest.TestCase):
    """InlineResponse200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """Test InlineResponse200"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse200()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
