"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.activites_aide_reussite import ActivitesAideReussite


class TestActivitesAideReussite(unittest.TestCase):
    """ActivitesAideReussite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivitesAideReussite(self):
        """Test ActivitesAideReussite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivitesAideReussite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
