"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.api.inscription_aux_cours_api import InscriptionAuxCoursApi  # noqa: E501


class TestInscriptionAuxCoursApi(unittest.TestCase):
    """InscriptionAuxCoursApi unit test stubs"""

    def setUp(self):
        self.api = InscriptionAuxCoursApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mini_formations_inscriptibles(self):
        """Test case for mini_formations_inscriptibles

        """
        pass


if __name__ == '__main__':
    unittest.main()
