"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.7
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.inscrire_a_une_mini_formation import InscrireAUneMiniFormation


class TestInscrireAUneMiniFormation(unittest.TestCase):
    """InscrireAUneMiniFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInscrireAUneMiniFormation(self):
        """Test InscrireAUneMiniFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InscrireAUneMiniFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
