"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.3
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_inscription_cours_sdk
from osis_inscription_cours_sdk.model.inscription_aun_cours import InscriptionAUnCours
globals()['InscriptionAUnCours'] = InscriptionAUnCours
from osis_inscription_cours_sdk.model.inscriptions_pour_une_mini_formation import InscriptionsPourUneMiniFormation


class TestInscriptionsPourUneMiniFormation(unittest.TestCase):
    """InscriptionsPourUneMiniFormation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInscriptionsPourUneMiniFormation(self):
        """Test InscriptionsPourUneMiniFormation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InscriptionsPourUneMiniFormation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
