# flake8: noqa

# import all models into this package
# if you have many models here with many references from one model to another this may
# raise a RecursionError
# to avoid this, import only the models that you directly need like:
# from from osis_inscription_cours_sdk.model.pet import Pet
# or import this package, but before doing it, use:
# import sys
# sys.setrecursionlimit(n)

from osis_inscription_cours_sdk.model.accepted_language_enum import AcceptedLanguageEnum
from osis_inscription_cours_sdk.model.activites_aide_reussite import ActivitesAideReussite
from osis_inscription_cours_sdk.model.autorise_inscrire_aux_cours import AutoriseInscrireAuxCours
from osis_inscription_cours_sdk.model.complement_de_formation import ComplementDeFormation
from osis_inscription_cours_sdk.model.contact_faculte import ContactFaculte
from osis_inscription_cours_sdk.model.cours import Cours
from osis_inscription_cours_sdk.model.demande_activites_aide_reussite import DemandeActivitesAideReussite
from osis_inscription_cours_sdk.model.demande_particuliere import DemandeParticuliere
from osis_inscription_cours_sdk.model.error import Error
from osis_inscription_cours_sdk.model.formulaire_inscription_cours import FormulaireInscriptionCours
from osis_inscription_cours_sdk.model.formulaire_proposition_programme_annuel import FormulairePropositionProgrammeAnnuel
from osis_inscription_cours_sdk.model.formulaire_proposition_programme_annuel_demandes_particulieres_dans_mini_formations import FormulairePropositionProgrammeAnnuelDemandesParticulieresDansMiniFormations
from osis_inscription_cours_sdk.model.formulaire_proposition_programme_annuel_inscriptions_dans_mini_formations import FormulairePropositionProgrammeAnnuelInscriptionsDansMiniFormations
from osis_inscription_cours_sdk.model.groupement import Groupement
from osis_inscription_cours_sdk.model.inline_response200 import InlineResponse200
from osis_inscription_cours_sdk.model.inscription_aun_cours import InscriptionAUnCours
from osis_inscription_cours_sdk.model.inscription_mini_formation import InscriptionMiniFormation
from osis_inscription_cours_sdk.model.inscriptions_aun_partenariat import InscriptionsAUnPartenariat
from osis_inscription_cours_sdk.model.inscriptions_pour_une_mini_formation import InscriptionsPourUneMiniFormation
from osis_inscription_cours_sdk.model.inscrire_a_une_mini_formation import InscrireAUneMiniFormation
from osis_inscription_cours_sdk.model.liste_mini_formations import ListeMiniFormations
from osis_inscription_cours_sdk.model.mini_formation import MiniFormation
from osis_inscription_cours_sdk.model.pae_valide_jury import PaeValideJury
from osis_inscription_cours_sdk.model.pae_valide_jury_links import PaeValideJuryLinks
from osis_inscription_cours_sdk.model.pdf_en_cours import PdfEnCours
from osis_inscription_cours_sdk.model.periode_inscription_etudiant import PeriodeInscriptionEtudiant
from osis_inscription_cours_sdk.model.programme_annuel_etudiant import ProgrammeAnnuelEtudiant
from osis_inscription_cours_sdk.model.proposition_pae import PropositionPae
from osis_inscription_cours_sdk.model.proposition_pae_links import PropositionPaeLinks
from osis_inscription_cours_sdk.model.unite_enseignement_avec_prerequis import UniteEnseignementAvecPrerequis
