# flake8: noqa

"""
    Course enrollments service

    A set of API endpoints that allow you to enroll students to courses  # noqa: E501

    The version of the OpenAPI document: 1.1
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.1"

# import ApiClient
from osis_inscription_cours_sdk.api_client import ApiClient

# import Configuration
from osis_inscription_cours_sdk.configuration import Configuration

# import exceptions
from osis_inscription_cours_sdk.exceptions import OpenApiException
from osis_inscription_cours_sdk.exceptions import ApiAttributeError
from osis_inscription_cours_sdk.exceptions import ApiTypeError
from osis_inscription_cours_sdk.exceptions import ApiValueError
from osis_inscription_cours_sdk.exceptions import ApiKeyError
from osis_inscription_cours_sdk.exceptions import ApiException
